version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_DB: jbpm
  
  jbpm:
    image: jboss/jbpm-server-full
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    ports:
    - 8080:8080
    - 8001:8001
    depends_on:
    - postgres

volumes:
  postgres_data:
    driver: local

